site_name: Material for "Base Python"
site_description: Материалы по курсу "Основы Python"
site_url:  ""
theme:
  name: material
  palette:
    primary: 'indigo'
    accent: 'indigo'

nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Types: types.md